#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "grav"
name = "Grav"
description.en = "Modern open source flat-file CMS"
description.fr = "CMS moderne basé sur des fichiers plats"

version = "2.0.20~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://www.getgrav.org/"
demo = "https://getgrav.org/downloads/themes"
admindoc = "https://learn.getgrav.org"
code = "https://github.com/getgrav/grav"
cpe = "cpe:2.3:a:getgrav:grav"
fund = "https://opencollective.com/grav"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/grav"

    [install.init_main_permission]
    help.en = "Will anyone be able to access the website?"
    help.fr = "Est-ce que quiconque pourra accéder au site ?"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en_EN", "fr_FR"]
    default = "fr_FR"

    [install.init_admin_permission]
    ask.en = "Select an administrator for the app"
    ask.fr = "Sélectionnez un administrateur pour l'application"
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.ldap]
    url = "https://github.com/trilbymedia/grav-plugin-login-ldap/archive/refs/tags/1.2.3.tar.gz"
    sha256 = "0d6312a3af552fd36f4fa8beab3a98b424c165468f01085da47090069950da6d"
    autoupdate.strategy = "latest_github_tag"
    autoupdate.upstream = "https://github.com/trilbymedia/grav-plugin-login-ldap"

    [resources.sources.main]
    url = "https://github.com/getgrav/grav/releases/download/2.0.20/grav-admin-v2.0.20.zip"
    sha256 = "cce22c4f51bec52b1eccd2e2cff05179f9030084d0e5b9efe85c7a251a294518"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "grav-admin.*.zip"

    [resources.sources.app-upgrade]
    url = "https://github.com/getgrav/grav/releases/download/2.0.20/grav-update-v2.0.20.zip"
    sha256 = "0bf3b4d39de59bc7f6f4ad720170478e397a0934e8af673b8cf8205a63897b8a"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "grav-update.*.zip"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    admin.url = "/admin"
    admin.additional_urls = ["/admin"]
    admin.allowed = "admins"
    user.show_tile = false

    [resources.apt]
    packages = "php8.5-fpm, php8.5-zip, php8.5-mbstring, php8.5-curl, php8.5-common, php8.5-dom, php8.5-gd, php8.5-xml, php8.5-ldap, php8.5-sqlite3, php8.5-mysql, php8.5-intl, php8.5-yaml, php8.5-apcu, php8.5-memcache, php8.5-memcached, php8.5-redis"
