#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "grav"
name = "Grav"
description.en = "Modern open source flat-file CMS"
description.fr = "CMS moderne basé sur des fichiers plats"

version = "1.7.52~ynh2"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://www.getgrav.org/"
demo = "https://getgrav.org/downloads/themes"
admindoc = "https://learn.getgrav.org"
code = "https://github.com/getgrav/grav"
cpe = "cpe:2.3:a:getgrav:grav"
fund = "https://opencollective.com/grav"

[integration]
yunohost = ">= 12.1.38"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/grav"

    [install.init_main_permission]
    help.en = "Will anyone be able to access the website?"
    help.fr = "Est-ce que quiconque pourra accéder au site ?"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en_EN", "fr_FR"]
    default = "fr_FR"

    [install.init_admin_permission]
    ask.en = "Select an administrator for the app"
    ask.fr = "Sélectionnez un administrateur pour l'application"
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.ldap]
    url = "https://github.com/trilbymedia/grav-plugin-login-ldap/archive/refs/tags/v1.2.1.tar.gz"
    sha256 = "204f3b931c68024bc3a0540a2693de39eabf2fab0ba019810e3740d3bc929d20"
    autoupdate.strategy = "latest_github_tag"
    autoupdate.upstream = "https://github.com/trilbymedia/grav-plugin-login-ldap"

    [resources.sources.main]
    url = "https://github.com/getgrav/grav/releases/download/1.7.52/grav-admin-v1.7.52.zip"
    sha256 = "e8aa1afb6d6969a845ad8da2653bee3eab9a4a7367fe90871e37377f412b3c35"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "grav-admin.*.zip"

    [resources.sources.app-upgrade]
    url = "https://github.com/getgrav/grav/releases/download/1.7.52/grav-update-v1.7.52.zip"
    sha256 = "e59b385d8bba8bf671aa96218ae2eb821d6e3857e57140f4c9dcd43080280388"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "grav-update.*.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.show_tile = false
    user.show_tile = false

    [resources.apt]
    packages = "php8.4-fpm, php8.4-zip, php8.4-mbstring, php8.4-curl, php8.4-dom, php8.4-gd, php8.4-xml, php8.4-ldap, php8.4-sqlite3, php8.4-mysql, php8.4-intl, php8.4-yaml"
