#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "grav"
name = "Grav"
description.en = "Modern open source flat-file CMS"
description.fr = "CMS moderne basé sur des fichiers plats"

version = "2.0.10~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://www.getgrav.org/"
demo = "https://getgrav.org/downloads/themes"
admindoc = "https://learn.getgrav.org"
code = "https://github.com/getgrav/grav"
cpe = "cpe:2.3:a:getgrav:grav"
fund = "https://opencollective.com/grav"

[integration]
yunohost = ">= 12.1.38"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/grav"

    [install.init_main_permission]
    help.en = "Will anyone be able to access the website?"
    help.fr = "Est-ce que quiconque pourra accéder au site ?"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en_EN", "fr_FR"]
    default = "fr_FR"

    [install.init_admin_permission]
    ask.en = "Select an administrator for the app"
    ask.fr = "Sélectionnez un administrateur pour l'application"
    type = "user"

[resources]
    [resources.sources]
    [resources.sources.ldap]
    url = "https://github.com/trilbymedia/grav-plugin-login-ldap/archive/refs/tags/1.2.1.tar.gz"
    sha256 = "204f3b931c68024bc3a0540a2693de39eabf2fab0ba019810e3740d3bc929d20"
    autoupdate.strategy = "latest_github_tag"
    autoupdate.upstream = "https://github.com/trilbymedia/grav-plugin-login-ldap"

    [resources.sources.main]
    url = "https://github.com/getgrav/grav/releases/download/2.0.10/grav-admin-v2.0.10.zip"
    sha256 = "bfa2cb7e26b4df5e1bf18eceea1ae04bd5ce1ef64cc0eef2ff5d89116eb1915e"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "grav-admin.*.zip"

    [resources.sources.app-upgrade]
    url = "https://github.com/getgrav/grav/releases/download/2.0.10/grav-update-v2.0.10.zip"
    sha256 = "2ace35613008352d394ce966d076dcbaa8f6e66764f7171f248cde5056dc944c"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "grav-update.*.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false
    admin.show_tile = false
    user.show_tile = false
    #api.url = "/api"
    #api.allowed = "visitors"
    #api.auth_header = false

    [resources.apt]
    packages = "php8.5-fpm, php8.5-zip, php8.5-mbstring, php8.5-curl, php8.5-common, php8.5-dom, php8.5-gd, php8.5-xml, php8.5-ldap, php8.5-sqlite3, php8.5-mysql, php8.5-intl, php8.5-yaml"
