#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#REMOVEME? ynh_abort_if_errors

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__password() {
    if [ "$password" == "" ]
    then
        ynh_app_setting_set --key=password --value="$password"
    fi
}

#=================================================

ynh_app_config_validate() {
    _ynh_app_config_validate

    if [ "${changed[with_sftp]}" == "true" ] && [ $with_sftp -eq 1 ] && [ "$password" == "" ]
    then
        ynh_die "You need to set a password to enable SSH and SFTP"
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    if [ "${changed[with_sftp]}" == "true" ] && [ $with_sftp -eq 1 ]
    then
        ynh_system_user_add_group --username=$app --groups="sftp.app ssh.app"
        usermod --shell /bin/bash $app

        if [ ! "$password" == "" ]
        then
            chpasswd <<< "${app}:${password}"
        fi
    elif [ "${changed[with_sftp]}" == "true" ] && [ $with_sftp -eq 0 ]
    then
        ynh_system_user_del_group --username=$app --groups="sftp.app ssh.app"
        usermod --shel /usr/sbin/nologin $app
    fi
}

ynh_app_config_run $1
