#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

# Initialize the with_sftp setting for the config panel
ynh_app_setting_set --app=$app --key=with_sftp --value="false"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=2

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/user/plugins/login-ldap" --source_id="ldap"

# Set permissions on app files
chown -R $app:www-data "$install_dir"
find "$install_dir" -type f -exec chmod 640 {} \;
find "$install_dir/bin" -type f -exec chmod 750 {} \;
find "$install_dir" -type d -exec chmod 750 {} \;
find "$install_dir" -type d -exec chmod +s {} \;

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=3

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=medium --footprint=medium

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

# Preparing config
ynh_exec_as $app mkdir -p "$install_dir/user/config/plugins/login-ldap"
ynh_exec_as $app touch "$install_dir/user/accounts/admin.yaml"

# Setting up config
ynh_add_config --template="../conf/login-ldap.yaml" --destination="$install_dir/user/config/plugins/login-ldap.yaml"
chown $app:$app "$install_dir/user/config/plugins/login-ldap.yaml"
chmod 640 "$install_dir/user/config/plugins/login-ldap.yaml"

#=================================================
# CREATE A CRON TASK
#=================================================
ynh_script_progression --message="Creating a cron task..." --weight=1

echo "* *  *  *  * $app php$phpversion $install_dir/bin/grav scheduler 1>> /dev/null 2>&1" > /etc/cron.d/$app

chmod 644 /etc/cron.d/$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
