#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

# Initialize the SFTP setting for the config panel
ynh_app_setting_set --key=with_sftp --value="false"
ynh_app_setting_set --key=password --value=$(ynh_string_random)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/user/plugins/login-ldap" --source_id="ldap"

# Set permissions on app files
#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
find "$install_dir" -type f -exec chmod 640 {} \;
find "$install_dir/bin" -type f -exec chmod 750 {} \;
find "$install_dir" -type d -exec chmod 750 {} \;
find "$install_dir" -type d -exec chmod +s {} \;

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

# Create a dedicated PHP-FPM config
ynh_app_setting_set --key=fpm_footprint --value="medium"
ynh_app_setting_set --key=fpm_usage --value="medium"
ynh_config_add_phpfpm

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# Preparing config
ynh_exec_as_app mkdir -p "$install_dir/user/config/plugins/login-ldap"
ynh_exec_as_app touch "$install_dir/user/accounts/admin.yaml"

# Setting up scheduler config
ynh_config_add --template="scheduler.yaml" --destination="$install_dir/user/config/scheduler.yaml"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/user/config/scheduler.yaml"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 640 "$install_dir/user/config/scheduler.yaml"

# Setting up LDAP config
ynh_config_add --template="login-ldap.yaml" --destination="$install_dir/user/config/plugins/login-ldap.yaml"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/user/config/plugins/login-ldap.yaml"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 640 "$install_dir/user/config/plugins/login-ldap.yaml"

#=================================================
# CREATE A CRON TASK
#=================================================
ynh_script_progression "Creating a cron task..."

echo "* *  *  *  * $app php$php_version $install_dir/bin/grav scheduler 1>> /dev/null 2>&1" > /etc/cron.d/$app

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 644 /etc/cron.d/$app

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
