#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

source .fonctions	# Loads the generic functions usually used in the script
source /usr/share/yunohost/helpers # Source YunoHost helpers

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Retrieve app settings
domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
admin=$(ynh_app_setting_get "$app" admin)
is_public=$(ynh_app_setting_get "$app" is_public)
language=$(ynh_app_setting_get "$app" language)

CHECK_PATH	# Checks and corrects the syntax of the path.

# Check if admin is not null
if [[ "$admin" = "" || "$is_public" = "" || "$language" = "" ]]; then
    echo "Unable to upgrade, please contact support"
    ynh_die
fi

final_path=/var/www/$app

db_name=$app

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*

if [ $is_public = "Yes" ];
then
	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/$app.conf
else
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
fi

# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]]; then
	# See install script
	ynh_app_setting_set "$app" unprotected_uris "/"
	sudo cp ../conf/nginx.conf-public /etc/nginx/conf.d/$domain.d/$app.conf
else
	sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
fi

# Reload Nginx
sudo service nginx reload
